apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      volumes:
      - name: front-pv-storage
        persistentVolumeClaim:
          claimName: front-pvc
      containers:
          - name: {{ .Chart.Name }}-{{ .Values.cacheContainer.name }}
            image: {{ .Values.cacheContainer.image }}
            ports:
              - containerPort: {{ .Values.cacheContainer.port }}
          - name: {{ .Chart.Name }}-{{ .Values.backendContainer.name }}
            image: {{ .Values.backendContainer.image }}
            ports:
              - containerPort: {{ .Values.backendContainer.port }}
          - name: {{ .Chart.Name }}-{{ .Values.dbContainer.name }}
            image: {{ .Values.dbContainer.image }}
            ports:
              - containerPort: {{ .Values.dbContainer.port }}
            env:
              {{- range .Values.dbContainer.env }}
              - name: {{ .name }}
                value: {{ .value | quote }}
              {{- end }}
          - name: {{ .Chart.Name }}-{{ .Values.frontContainer.name }}
            image: {{ .Values.frontContainer.image }}:{{ .Values.frontContainer.imageTag }}
            ports:
              - containerPort: {{ .Values.frontContainer.port }}
            volumeMounts:
              - mountPath: "/var/www/html/storage/logs"
                name: front-pv-storage
